config/routes.rb
Rails.application.routes.draw do
  root to: 'static#index'
  get :register, to: 'register_users#new'
  post :register, to: 'register_users#create'
  get :login, to: 'authenticate#new'
  post :login, to: 'authenticate#create'
  get :logout, to: 'authenticate#destroy'

  resources :tweets, only: [:new, :create]

  namespace :ajax do
    resources :tweets, only: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
# == Schema Information
#
# Table name: tweets
#
#  id       :bigint(8)        not null, primary key
#  content  :string(255)      default(""), not null
#  users_id :bigint(8)        not null
#

class Tweet < ApplicationRecord
  validates :content, presence: true, length: { maximum: 255 }

  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id      :bigint(8)        not null, primary key
#  name    :string(255)      default(""), not null
#  id_name :string(255)      default(""), not null
#

class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 255 }
  validates :id_name, presence: true, length: { maximum: 255 }, uniqueness: true

  has_many :tweets, dependent: :destroy, inverse_of: :user
end

app/controllers/ajax/tweets_controller.rb
class Ajax::TweetsController < AjaxController
  def index
    tweets = Tweet.all
    render json: { status: 200, data: tweets }
  end
end

app/controllers/ajax_controller.rb
class AjaxController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def login(user)
      session[:user_id] = user.id
    end

    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end

    def logout
      session[:user_id] = nil
      @current_user = nil
    end

    def logged_in?
      redirect_to login_path unless current_user
    end
end

app/controllers/authenticate_controller.rb
class AuthenticateController < ApplicationController

  def new
  end
  def create
    @user = User.find_by(id_name: params[:id_name])
    if @user
      login @user
      redirect_to root_path
    else
      redirect_to login_path
    end
  end
  def destroy
    logout
    redirect_to login_path
  end
end

app/controllers/register_users_controller.rb
class RegisterUsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)

    if @user.save
      login @user
      redirect_to root_path
    else

    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :id_name)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  before_action do
    logged_in?
  end
  def index
    @tweets = Tweet.all
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :logged_in?

  def new
  end
  def create
    @tweet = current_user.tweets.build(content: params[:content])
    if @tweet.save
      redirect_to root_path
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/register_users_helper.rb
module RegisterUsersHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/authenticate/new.html.erb
<div class="container">
  <%= form_with url: login_path do |f| %>
    <div>
      アカウント名:<%= f.text_field :id_name %>
    </div>
    <div>
      <%= f.submit '送信' %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/register_users/new.html.erb
<div class="container">
  <%= form_with model: @user, url: register_path do |f| %>
    <div>
      名前: <%= f.text_field :name, placeholder: 'name' %>
    </div>
    <div>
      アカウント名:<%= f.text_field :id_name, placeholder: 'account_name' %>
    </div>
    <div>
      <%= f.submit '送信' %>
    </div>
  <% end %>
</div>

app/views/tweets/new.html.erb
<div class="container">
  <%= form_with url: tweets_path do |f| %>
    <div>
      <%= f.text_area :content, size: '20x10' %>
    </div>
    <div>
      <%= f.submit '送信' %>
    </div>
  <% end %>
</div>